### ISSUE TITLE
有关openKE

### ISSUE THREAD

**Issue by xby1** [t170815518/Game_WebSocket#2]
您好，我是中南大学在读研究生，目前正在研究知识图谱表示学习，我有看到您和我遇到相同问题（wiidata_300k），想请教您怎么解决的？谢谢！

**Comment by t170815518** [comment]
你好，请问具体是什么问题？

**Comment by xby1** [comment]
您好您好，很感谢您的回复！
我最近在openKE上跑wikidata_300k数据集出现了问题，想要咨询您是否成功跑通？
我的问题如下：

在加载训练数据集的时候报错，无法向下执行。


如果方便，能否加您微信？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "t170815518/Game_WebSocket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [t170815518/Game_WebSocket] 有关openKE (#2)





 
你好，请问具体是什么问题？

**Comment by t170815518** [comment]
> 您好您好，很感谢您的回复！ 我最近在openKE上跑wikidata_300k数据集出现了问题，想要咨询您是否成功跑通？ 我的问题如下： 在加载训练数据集的时候报错，无法向下执行。 如果方便，能否加您微信？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "t170815518/Game_WebSocket" ***@***.***&gt;; 发送时间:&nbsp;2021年4月27日(星期二) 晚上7:37 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [t170815518/Game_WebSocket] 有关openKE (#2) 你好，请问具体是什么问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我的微信是t170815518
